### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RadNotRed** [Penguin-Spy/powercord-ppl-moe#1]
You cannot click on the connection for the website in the user profile. 
![z3ApgKov](https://user-images.githubusercontent.com/80015713/119888200-13078880-bf03-11eb-9c1f-12ee9eeda042.gif)

**Comment by Penguin-Spy** [comment]
I can't seem to produce this issue, but it looks like a problem with the Badges Everywhere plugin or a theme.
Could you send: what theme(s) you're using, a screenshot of the whole profile screen (so i can see where this is happening), and if you're using the Badges Everywhere plugin.

**Comment by RadNotRed** [comment]
> I can't seem to reproduce this issue, but it looks like a problem with the Badges Everywhere plugin or a theme.
> Could you send: what theme(s) you're using, a screenshot of the whole profile screen (so i can see where this is happening), and if you're using the Badges Everywhere plugin.

I'm only using AMOLED-cord, I don't have status everywhere, etc. 
![image](https://user-images.githubusercontent.com/80015713/119894001-0e929e00-bf0a-11eb-9125-2c75304c9b06.png)

**Comment by RadNotRed** [comment]
okay yeah, its amoledcord _i shoulve tried turning off the theme_  my bad haha

**Comment by RadNotRed** [comment]
okay nevermind, its userbg and since amoledcord has userbg support that's what breaks it

**Comment by Penguin-Spy** [comment]
huh. i installed amoledcord, but even with the "Custom Profiles Premium" experiment enabled i'm still getting the old layout for the user modal, with the badges in the right place.
![image](https://user-images.githubusercontent.com/42628520/119896953-9e2d5200-bef4-11eb-8797-0c12ff33b4fa.png)
I might not be able to fix this until discord rolls out the new layout to everyone :/
I also can't click the link using amoledcord, but that seems to be a problem with the theme.
If you disable the ppl.moe plugin, do the badges move to a different connection box, or where do they show up?

**Comment by RadNotRed** [comment]
That's all that moves, it gets put in place where Minecraft connections are where you cant click

![DiscordCanary_fmfMAImk2C](https://user-images.githubusercontent.com/80015713/119899288-ef4b3f00-bf10-11eb-9c6a-a6c379167e57.png)
![DiscordCanary_hDFGkGPXgF](https://user-images.githubusercontent.com/80015713/119899289-f07c6c00-bf10-11eb-8651-7b1141df5e29.png)

**Comment by Penguin-Spy** [comment]
wait, so is the problem not being able to click the link on amoledcord, or the badges being in the wrong spot? because the badges seem to be in the right spot in both of your later images.
if the problem is not being able to click the link, I did some testing and found it happens with all connections made by the Powercord Connections API. that is a problem with the theme, not my plugin, and you'd have to make an issue on their GitHub.
(specifically, the colored background on the boxes is overlapping the link because the Powercord links have slightly different css than the discord ones).

**Comment by RadNotRed** [comment]
> wait, so is the problem not being able to click the link on amoledcord, or the badges being in the wrong spot? because the badges seem to be in the right spot in both of your later images.
> if the problem is not being able to click the link, I did some testing and found it happens with all connections made by the Powercord Connections API. that is a problem with the theme, not my plugin, and you'd have to make an issue on their GitHub.
> (specifically, the colored background on the boxes is overlapping the link because the Powercord links have slightly different css than the discord ones).

the problem is not being able to click it on amoledcord, so yeah, its a problem with the theme ill let him know eventually
thanks for the help

**Comment by Penguin-Spy** [comment]
no problem!
