### ISSUE TITLE
It may no longer work?

### ISSUE THREAD

**Issue by SheepCommander** [Penguin-Spy/powercord-ppl-moe#7]
**Describe the bug**
Can't see any ppl.moe tab
![image](https://user-images.githubusercontent.com/66646514/148765037-0b3208e1-f35a-48a6-9295-c5dc22427b16.png)

**To Reproduce**
1. Go to 'a user'
2. Click on 'them then go to Profile'
3. Scroll down to 'no scroll!'
4. See no tab

**Plugins**
I currently have 59 plugins but do not have PronounDB

**Themes**
None

**Other**
win11
![image](https://user-images.githubusercontent.com/66646514/148765163-fa783cce-8cd2-464f-b83e-44c86b260aa6.png)

![image](https://user-images.githubusercontent.com/66646514/148765169-a722720e-994f-4a49-9875-fac9c21580db.png)

**Comment by Penguin-Spy** [comment]
Thanks for the detailed report! After some debugging, it appears Discord did a pretty large rewrite and the plugin is no longer able to inject into the user profile, meaning the tab is gone. It might take a couple days to fix because of that rewrite.

**Comment by SheepCommander** [comment]
I heard about that too, thanks!

**Comment by sp96296** [comment]
I understand it was a pretty big rewrite, so no pressure, but any update on this? Love your program, especially since ppl.moe covers neopronouns where pronoundb doesnt cover those.

**Comment by Penguin-Spy** [comment]
sorry about the delay on this fix, the update involved yet another rewrite of the user profile modal, and finals week was coming up so i had to focus on that instead.

**Comment by sp96296** [comment]
forgot to reply - no worries at all. Thanks for the update, I hope finals went well!
